### ISSUE TITLE
PicoTTS language cannot be changed

### ISSUE THREAD

**Issue by hawkeye217** [rhasspy/rhasspy-tts-cli-hermes#2]
I'm on a master/satellite configuration on Docker with ``2.5-pre`` and an ``en`` profile and the language that PicoTTS outputs is always ``en-US``, no matter what I have set in the UI or in my ``profile.json``.

For example, if I set the language to ``fr-FR`` in my profile on the master (where TTS is handled), the log file still shows me that the command that generates the wav file is using ``en-US``.

```
[DEBUG:2020-04-16 01:31:11,368] rhasspytts_cli_hermes: ['bash', '-c', 't=$(mktemp --suffix .wav); function x() { rm -f $t; }; trap x EXIT; pico2wave -l en-US -w $t "$0"; cat $t', 'Bonjour.']
```

Running the command ``pico2wave -l fr-FR -w /tmp/foo.wav "Bonjour"`` inside the Docker container generates the wav file in French, as expected.

Let me know if you need any more info.  Thanks!

**Comment by synesthesiam** [comment]
Hopefully fixed by now!

**Comment by hawkeye217** [comment]
This is still an issue on the latest 2.5-pre docker image as of 5/13/20.  Is this just the case where it's fixed somewhere else and the Docker image just hasn't been updated yet?

**Comment by synesthesiam** [comment]
I think so, yes. I will be uploading a new version this week.

**Comment by hawkeye217** [comment]
Great!  I'll test it after you release it and let you know.  Thanks!

**Comment by hawkeye217** [comment]
I noticed you pushed a new ``2.5.0-pre`` Docker image a couple of days ago - any chance of a new ``2.5.0-pre-arm32v6`` image?

**Comment by synesthesiam** [comment]
The `armv6` image should be embedded now in the main image. I'm having to force the platform to get it to work, though:

```bash
docker pull --platform linux/arm/v6 rhasspy/rhasspy:2.5.0-pre
```

**Comment by hawkeye217** [comment]
Got it. This is a bit of a bummer.

```
"--platform" is only supported on a Docker daemon with experimental features enabled
```

Will poke around to see if there's another way or workaround.

**Comment by hawkeye217** [comment]
Didn't realize it was super easy to enable experimental features for the Docker daemon. (https://thenewstack.io/how-to-enable-docker-experimental-features-and-encrypt-your-login-credentials/)

Pulling new images now!

**Comment by hawkeye217** [comment]
Pulled the latest Docker images and PicoTTS still does not work if I set the language to something else as per my original post :(

**Comment by synesthesiam** [comment]
Please try again and re-open the issue if it's still a problem.
